pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["add_advanced_detection_cameras.htm","Add Advanced Detection Cameras","Add Advanced Detection Cameras Advanced detection cameras are secondary cameras that measures traffic volume that is set back a user-specified dis...",""],
["add_all_of_an_intersections_ca.htm","Add all of an Intersection’s Cameras","Add all of an Intersection’s Cameras To add cameras to the intersection: 1. Click the + Camera button. The Configure Camera dialog box displays. 2...",""],
["add_an_insyncfusion_intersecti.htm","Configure an InSync:Fusion Intersection","Configure an In|Sync:Fusion Intersection For In|Sync:Fusion, you must complete the following steps to fully configure vehicle detection for each d...",""],
["add_a_custom_camera_to_a_colum.htm","Add a Custom Camera to a Column","Add a Custom Camera to a Column Instead of displaying all the cameras for an intersection within one column, you may want to display a camera in a...",""],
["add_a_map.htm","Add a Map","Add a Map To add a map for the management group: 1. Select Map from the + ADD menu. A row for adding a map displays at the bottom of the page. 2. ...",""],
["add_a_recording.htm","Add a Recording","Add a Recording To schedule the recording of an intersection’s camera view: NOTE: Videos can only be recorded to a USB device, such as a flash dri...",""],
["add_a_user.htm","Add a User","Add a User To create a new user account: 1. Click Edit Users from the Account menu. The Edit Users screen displays. 2. Click New User. The Add New...",""],
["add_corridors.htm","Add Corridors","Add Management Groups To manually add a management group: 1. Select Management Group from the + ADD menu. A row for adding a management group disp...",""],
["add_din_relays.htm","Add DIN Relays","Add DIN Relays To add DIN relays: 1. Click the + RELAY button. A row for adding a DIN relay displays at the bottom of the Intersection box. 2. Typ...",""],
["add_gaps_between_columns.htm","Add Gaps between Camera Views","Add Gaps between Camera Views You can add gaps between the camera views. This creates a separator between camera views. To add a gap between a cam...",""],
["add_intersections.htm","Add Intersections","Add Intersections To add intersections: 1. Click + INTERSECTION. A row for adding an intersection displays at the bottom of the page. 2. Type the ...",""],
["add_intersections2.htm","Add Intersections","Add Intersections To add a intersection: 1. Select Intersection from the + ADD menu. The Add Intersection dialog box displays. 2. Type the process...",""],
["add_or_remove_rows.htm","Add or Remove Rows","Add or Remove Rows You can also add or remove rows of camera views by selecting the Add Row and Delete Row buttons. ",""],
["auto_generate_a_portal.htm","Auto Generate a Portal","Auto Generate a Portal This option allows you to create a portal by using the latest management group configuration information on the processor a...",""],
["camera_basics.htm","Camera Basics","Camera Basics Within the In|Sync WebUI, you can choose to view traffic exactly as the view is coming off the camera (unprocessed) or by the defaul...",""],
["camera_detection_zone_setup.htm","Camera Detection Zone Setup","Camera Detection Zone Setup Draw one detection zone per lane. Do not include more than one lane in a detection zone. When feasible, draw detection...",""],
["camera_view_icons.htm","Camera View Icons","Camera View Icons Under certain conditions, you may see the following icons display on the camera view. These icons indicate certain failure condi...",""],
["camera_view_vs_cartoon_view.htm","Viewing the Cartoon View","Viewing the Cartoon View The Multi Camera view allows you to either view live images coming from all the cameras located at the intersection or yo...",""],
["change_camera_layout.htm","Change Camera Layout","Change View Styles The Multiple Camera view provides several different viewing styles, which can be selected from the View Styles drop-down list b...",""],
["change_corridor_view_content.htm","Change Corridor View Content","Change Management Group View Content To change the content or order of content that displays within the Management Group View, you can go into the...",""],
["change_gps_coordinates.htm","Change GPS Coordinates","Change GPS Coordinates GPS coordinates are usually set only once, when you initially set up the processor at an intersection. We recommend that GP...",""],
["chapter_2.htm","Getting started","Getting started Top Previous Next Enter topic text here. ",""],
["collapse_and_expand_intersecti.htm","Collapse and Expand Intersections","Collapse and Expand Intersections You can choose to collapse or expand the Intersection or Management Group content block to easily see what manag...",""],
["confirm_camera_detectors_are_a.htm","Confirm Camera/Detectors are Assigned Correctly","Confirm Camera/Detectors are Assigned Correctly After defining all In|Sync detection cameras and external detectors, verify that each camera/exter...",""],
["confirm_detection_cameras_are_.htm","Confirm Detection Cameras are Correctly Assigned","Confirm Detection Cameras are Correctly Assigned After defining all detection cameras, verify that each camera is assigned to the correct directio...",""],
["confirm_detectors_are_assigned.htm","Confirm Detectors are Assigned Correctly","Confirm Detectors are Assigned Correctly After defining all external detectors, verify that each external detector is assigned to the correct dire...",""],
["corridor_status.htm","Corridor Status","Status The Status page provides a real-time status of communications between In|Sync Processors within the management group, allowing you to troub...",""],
["count_totals.htm","Count Totals","Count Totals The Count Totals report contains the number of vehicles that have traveled within the specified phase(s). This is based on In|Sync’s ...",""],
["create_a_corridor_view_for_the.htm","Create a Corridor View for the First Time","Create a Management Group View for the First Time When you first open the Management Group view, you will only see the camera views for the inters...",""],
["create_a_portal_the_first_time.htm","Create a Portal the First Time","Create a Portal the First Time When you first open the Portal, there are no links. You must first design the Portal in the Portal Designer. To des...",""],
["daily_summary_report.htm","Daily Summary Report","Daily Summary Report The Daily Summary report provides several pieces of information: Intersection Totals: Total vehicles counts for the selected ...",""],
["delete_a_scheduled_recording.htm","Delete a Scheduled Recording","Delete a Scheduled Recording To delete a scheduled recording (say that you accidentally selected the wrong camera): 1. Within the Recording Schedu...",""],
["delete_a_user.htm","Delete a User","Delete a User 1. From the user list, click the next to the name. The Delete User dialog box displays. 2. Click Yes when the confirmation prompt ap...",""],
["delete_cameras_and_gaps_from_t.htm","Delete Cameras and Gaps from the View","Delete Cameras and Gaps from the View To delete a camera or gap within the management group view designer, click the X icon next to the content th...",""],
["deploy_the_application.htm","Deploy the Application","Deploy the Application To deploy new code from Rhythm Engineering on to an In|Sync Processor, complete the following steps: 1. Select Maintenance ...",""],
["detector_naming.htm","Detector Naming","Detector Naming Verify that all detectors in the management group are labeled with meaningful names for identification purposes. Accepted symbols ...",""],
["download_statistics.htm","Download Statistics","Download Statistics You can also download statistics for viewing in another software program, such as Microsoft Excel. Before clicking Download St...",""],
["edit_content_in_the_portal_des.htm","Edit Content in the Portal Designer","Edit Content in the Portal Designer You can also change what management groups/intersections/camera views/maps are listed and the order in which t...",""],
["edit_users.htm","Edit Users","Edit Users 1. Select Edit Users from the Account menu. The Edit Users screen displays. 2. From the user list, click the button next to the user na...",""],
["enlarge_and_condense_camera_vi.htm","Enlarge and Condense Camera Views","Enlarge and Condense Camera Views The views can be enlarged or reduced by clicking the magnify icons, which are located on the top right side of t...",""],
["external_detector_setup_insync.htm","External Detector Setup (InSync/InSync:Fusion)","External Detector Setup (In|Sync/In|Sync:Fusion) Verify that distances between stop bar and detectors are accurate. Inaccurate measurements will l...",""],
["generate_a_daily_summary_repor.htm","Generate a Daily Summary Report","Generate a Daily Summary Report To generate a Daily Summary report: 1. Select Daily Summary from the Dashboard or from the Reports menu. 2. Click ...",""],
["generate_a_historical_report.htm","Generate a Historical Report","Generate a Historical Report To generate historical data: 1. Select History Viewer from the Reports menu. 2. Either type the start date and time i...",""],
["grab_camera_backgrounds.htm","Grab Camera Backgrounds","Grab Camera Backgrounds NOTE: The following instructions pertain only to In|Sync, In|Sync:Fusion and In|Sync:Thermal installations. After creating...",""],
["history_viewer.htm","History Viewer","History Viewer The In|Sync Processor collects and saves operational information into a historical log. This log can then be used for future use an...",""],
["how_does_corridor_status_work_.htm","How does Corridor Status work?","How does Status work? The Status page is updated by processors coordinating with each other via communications. This information is reported as fr...",""],
["how_does_it_work_.htm","How Does the Corridor View Work?","How Does the Management Group View Work? The Management Group view is also user-customized, meaning that you can define exactly what intersection(...",""],
["how_does_the_portal_view_work_.htm","How does the Portal work?","How does the Portal work? Portal is user-customizable, meaning that you can define exactly what management group, intersection, camera, DIN relay,...",""],
["how_insync_works.htm","How InSync Works","How In|Sync Works Traffic coordination at an intersection has traditionally been managed by a cabinet’s traffic controller using timing plans crea...",""],
["how_to_use_corridor_status.htm","How to use Corridor Status","How to use Status The Status page is available to all users by selecting Status from the Management Group menu. ",""],
["how_to_use_corridor_view.htm","How to use Corridor View","How to use Management Group View Before using the Management Group view, you must define what intersections and cameras you want shown on the Mana...",""],
["how_to_use_the_portal_view.htm","How to use the Portal","How to use the Portal Before using the Portal, you must define what management groups, intersections, cameras, DIN Relays and Map View links you w...",""],
["html_about_wolf_io_1.htm","About Wolf IO","About WolfIO WolfIO is InSync&#39;s volume analyzer software. Is is for use by Rhythm personnel only. ",""],
["html_accessing_cameraio_1.htm","Access CameraIO","Access CameraIO CameraIO refers to the part of the InSync software that reads and processes images coming from each camera (video detection), whic...",""],
["html_accessing_insync_1.htm","Access InSync on the processor","Access InSync on the processor You may also access the InSync software on the processor by selecting InSync from the Advanced screen. This option ...",""],
["html_accessing_io_test_1.htm","Use IO Test","Use IO Test The IO-Board Tester can be used to confirm hardware connections, map inputs from the detectors to outputs to the controller, and/or di...",""],
["html_add_and_configure_detection_ca.htm","Add InSync Detection Cameras","Add In|Sync Detection Cameras NOTE: The following instructions pertain only to In|Sync, In|Sync:Fusion and In|Sync:Thermal installations. In|Sync ...",""],
["html_add_and_configure_detection_ca_2.htm","Add and Configure Detection Cameras","Add Detection Cameras The following instructions pertain only to InSync and InSync:Fusion installations. To define that an InSync detection camera...",""],
["html_add_a_monitoring_camera.htm","Add a Monitoring Camera","Add a Monitoring Camera NOTE: The following instructions pertain only to In|Sync:Tesla installations. For troubleshooting purposes, Rhythm Enginee...",""],
["html_add_a_monitoring_camera_2.htm","Add a monitoring camera","Add a monitoring camera NOTE: The following instructions pertain only to InSync:Tesla installations. For troubleshooting purposes, Rhythm Engineer...",""],
["html_add_detection_zones.htm","Add Detection Zones","Add Detection Zones NOTE: The following instructions pertain only to In|Sync, In|Sync:Fusion and In|Sync:Thermal installations. The proper placeme...",""],
["html_add_detection_zones_2.htm","Add detection zones","Add detection zones NOTE: The following instructions pertain only to InSync and InSync:Fusion installations. The proper placement of detection zon...",""],
["html_add_phases.htm","Add Phases","Add Phases NOTE: The following instructions mainly pertain to In|Sync:Tesla installations, but can be applicable to In|Sync and In|Sync:Fusion ins...",""],
["html_add_phases_2.htm","Add phases","Add phases NOTE: The following instructions mainly pertain to InSync:Tesla installations, but can be applicable to InSync and InSync:Fusion instal...",""],
["html_add_presence_segments.htm","Define Presence Segments","Define Presence Segments NOTE: The following instructions pertain only to In|Sync, In|Sync:Fusion and In|Sync:Thermal installations. At least two ...",""],
["html_add_presence_segments_2.htm","Define presence segments","Define presence segments The following instructions pertain only to InSync and InSync:Fusion installations. At least two segments in each detectio...",""],
["html_add_segment_lines.htm","Add Segment Lines","Add Segment Lines NOTE: The following instructions pertain only to In|Sync, In|Sync:Fusion and In|Sync:Thermal installations. Segment lines are ad...",""],
["html_add_segment_lines_2.htm","Add segment lines","Add segment lines NOTE: The following instructions pertain only to InSync and InSync:Fusion installations. Segment lines are added after detection...",""],
["html_assign_a_bypass_configuration_1.htm","Assign a bypass configuration","Assign a bypass configuration Note: Bypass configuration is only functional while both InSync and the IO board are online and communicating. If yo...",""],
["html_assign_lanes.htm","Assign Lanes","Assign Lanes NOTE: The following instructions mainly pertain to In|Sync:Tesla installations, but can be applicable to In|Sync and In|Sync:Fusion i...",""],
["html_assign_lanes_2.htm","Assign lanes","Assign lanes NOTE: The following instructions mainly pertain to InSync:Tesla installations, but can be applicable to InSync and InSync:Fusion inst...",""],
["html_camera_view_1.htm","Camera View","Camera and Cartoon Views The View button allows you to either view live images coming from all the cameras located at the intersection or a cartoo...",""],
["html_change_an_external_detectors_s.htm","Change an External Detector&#39;s Settings","Change an External Detector&#39;s Settings To change the settings assigned to a detector: 1. If the Configuration Utility is not open, select Configur...",""],
["html_change_an_external_detectors_s_2.htm","Change an external detector&#39;s settings","Change an external detector To change the settings assigned to a detector: 1. Click the external detector that you want to change. 2. Click the Ed...",""],
["html_change_a_directions_phase_1.htm","Change a Direction&#39;s Phase","Change a Direction&#39;s Phase To change which phase is assigned to a direction: 1. If the Configuration Utility is not open, select Configure Detecto...",""],
["html_change_camera_layout_1.htm","Change camera layout","Change camera layout The Multiple Camera view provides several different layouts for viewing live images, which can be selected from the Layouts d...",""],
["html_change_delete_detection_zone.htm","Change/Delete Detection Zone","Change/Delete Detection Zone To edit or remove a detection zone: 1. If the Configuration Utility is not open, select Configure Detectors from the ...",""],
["html_change_delete_detection_zone_2.htm","Change/delete detection zone","Change/delete detection zone To edit or remove a detection zone: 1. Click the Detection Zone button. 2. Select one of the zones in the list. The z...",""],
["html_configure_an_insynctesla_inter.htm","Configure an InSync:Tesla Intersection","Configure an In|Sync:Tesla Intersection For In|Sync:Tesla, you must complete the following steps to fully configure vehicle detection for each dir...",""],
["html_configure_an_insynctesla_inter_2.htm","Configure an InSync:Tesla intersection","InSync:Tesla configuration For InSync:Tesla, you must complete the following steps to fully configure vehicle detection for each direction: 1) Add...",""],
["html_configure_an_insync_insyncfusi.htm","Configure an InSync Intersection","Configure an In|Sync Intersection For In|Sync, you must complete the following steps to fully configure vehicle detection for each direction: 1. A...",""],
["html_configure_an_insync_insyncfusi_2.htm","Configure an InSync/InSync:Fusion intersection","InSync/InSync:Fusion configuration For InSync and InSync:Fusion, you must complete the following steps to fully configure vehicle detection for ea...",""],
["html_configure_an_insync_thermal.htm","Configure an InSync:Thermal Intersection","Configure an In|Sync:Thermal Intersection For In|Sync:Thermal systems, you must complete the following steps to fully configure vehicle detection ...",""],
["html_configure_external_detectors.htm","Add External Detectors","Add External Detectors NOTE: The following instructions pertain only to In|Sync:Fusion and In|Sync:Tesla installations. If no external detectors e...",""],
["html_configure_external_detectors_2.htm","Configure external detectors","Configure external detectors NOTE: The following instructions pertain only to InSync:Fusion installations. After defining the lanes within a phase...",""],
["html_configure_the_intersection_1.htm","Configure the Intersection","Configure the Intersection Clicking Configure Detectors from the Settings menu displays the Configure Detectors screen. To open the applet, click ...",""],
["html_configuring_shadow_filtering_1.htm","Use shadow filtering","Use shadow filtering Moving shadows can create false positive detections. To counter these situations where shadows may create false positives, yo...",""],
["html_confirm_camera_views2_1.htm","Confirm camera views","Confirm camera views In the current instructions (InSync 1.3), we need the user to go into CameraIO and select Raw Footage to obtain an image. Do ...",""],
["html_confirm_camera_views_1.htm","Confirm correct InSync operation","Confirm correct InSync operation After the inputs and outputs have all been set up, you need to confirm that InSync is working correctly. To verif...",""],
["html_confirm_edge_lines.htm","Confirm Edge Lines","Confirm Edge Lines NOTE: The following instructions pertain only to In|Sync and In|Sync:Fusion installations that use In|Sync video detection came...",""],
["html_confirm_edge_lines_2.htm","Confirm edge lines","Confirm edge lines NOTE: The following instructions pertain only to InSync and InSync:Fusion installations. To confirm that a certain object creat...",""],
["html_confirm_insync_operations_1.htm","Confirm InSync operations","Confirm InSync operations The following checks must be performed when initially turning on an InSync Processor: 1. Test hardware using the I/O Boa...",""],
["html_copyrights.htm","Copyrights","Copyrights &#169; 2015 Rhythm Engineering. All rights reserved. If this guide is distributed with software that includes an end-user agreement, this gu...",""],
["html_copyrights_2.htm","Copyrights","Copyrights &#169; 2013 Rhythm Engineering. All rights reserved. If this guide is distributed with software that includes an end-user agreement, this gu...",""],
["html_define_inputs_and_outputs_1.htm","Define inputs and outputs","Define inputs and outputs Pin(s)/signal(s) must be mapped in InSync in order for data to be received and in order for calls (outputs) to be placed...",""],
["html_define_the_failure_behavior_fo.htm","Define the failure behavior for InSync Processors containing POS boards","Define the failure behavior for InSync Processors containing POS boards One of the hardware components of the most recent style of InSync Processo...",""],
["html_delete_lanes.htm","Delete Lanes","Delete Lanes To remove a lane from a phase: 1. If the Configuration Utility is not open, select Configure Detectors from the Settings menu. The Co...",""],
["html_delete_lanes_1.htm","Delete lanes","Delete lanes To remove a lane from a phase: 1. Right-click the lane that you want to delete. 2. Select Delete from the shortcut menu. ",""],
["html_delete_phases.htm","Delete Phases","Delete Phases To delete a phase: 1. If the Configuration Utility is not open, select Configure Detectors from the Settings menu. The Configure Det...",""],
["html_delete_phases_1.htm","Delete phases","Delete phases To delete a phase: 1. Right-click the phase number in the tree view. 2. Select Delete from the shortcut menu. ",""],
["html_delete_segment_lines.htm","Delete Segment Lines","Delete Segment Lines To delete a single segment: 1. If the Configuration Utility is not open, select Configure Detectors from the Settings menu. T...",""],
["html_delete_segment_lines_1.htm","Delete segment lines","Delete segment lines To delete a single segment: 1. Click the Segment Line button. 2. Click Delete Segment. 3. Click on the segment you want to de...",""],
["html_detection_zone_tips.htm","Detection Zone Tips","Detection Zone Tips Draw detection zones inside the lane striping. Including lane striping can cause false positives if the camera shakes. Do not ...",""],
["html_detection_zone_tips_1.htm","Detection zone tips","Detection zone tips Draw detection zones inside the lane striping. Including lane striping can cause false positives if the camera shakes. Do not ...",""],
["html_edit_segment_lines.htm","Edit Segment Lines","Edit Segment Lines To edit a segment: 1. If the Configuration Utility is not open, select Configure Detectors from the Settings menu. The Configur...",""],
["html_edit_segment_lines_1.htm","Edit segment lines","Edit segment lines To edit a segment: 1. Click the Segment Line button. 2. Click Edit. 3. Click on one end of the segment line and drag it to its ...",""],
["html_enlarge_camera_view.htm","Enlarge camera view","Resize camera views The views can be enlarged or reduced by clicking the + and - buttons, which are located below the View tabs. ",""],
["html_fog_zone_tips.htm","Fog Zone Tips","Fog Zone Tips Fog zones can be drawn around objects that have high contrast with the background. Do not draw a single fog zone around multiple obj...",""],
["html_fog_zone_tips_1.htm","Fog zone tips","Fog zone tips Fog zones can be drawn around objects that have high contrast with the background. Do not draw a single fog zone around multiple obj...",""],
["html_index.htm","InSync Kiosk Help","This page requires frames Click here to view the table of contents without frames ",""],
["html_insync_kiosk_help_content_dyn.htm","InSync Kiosk Help","InSync Kiosk Help Contents | Index | Search About the InSync Kiosk Set up an InSync Processor Set the system name Set the NTP server Set network s...",""],
["html_insync_kiosk_help_content_static.htm","InSync Kiosk Help","InSync Kiosk Help Contents | Index About the InSync Kiosk Set up an InSync Processor Set the system name Set the NTP server Set network settings S...",""],
["html_insync_kiosk_help_ftsearch.htm","InSync Kiosk Help","InSync Kiosk Help Contents | Index | Search Enter one or more keywords to search (&#39;*&#39; and &#39;?&#39; wildcards are supported): You must have JavaScript e...",""],
["html_insync_kiosk_help_kwindex_dyn.htm","InSync Kiosk Help","InSync Kiosk Help Contents | Index | Search ",""],
["html_insync_kiosk_help_kwindex_static.htm","InSync Kiosk Help","InSync Kiosk Help Contents | Index ",""],
["html_introduction.htm","About the InSync Kiosk","About the InSync Kiosk The InSync Kiosk provides you with direct access to functionality on the InSync Processor while at the cabinet. You can use...",""],
["html_new_topic.htm","Back up an InSync configuration file","Back up a configuration file It is good practice to back up InSync configuration files each time you make a change to a configuration. This ensure...",""],
["html_pause_camera_images.htm","Pause camera images","Pause camera images To pause an image, click on the camera view. A paused icon displays over the camera view. Clicking the pause icon resumes the ...",""],
["html_rearrange_camera_views.htm","Rearrange camera views","Rearrange camera views You can move camera views around by clicking on a camera view and dragging it to the new position on the screen. To restore...",""],
["html_remove_fog_zones.htm","Remove Fog Zones","Remove Fog Zones To remove fog zones: 1. If the Configuration Utility is not open, select Configure Detectors from the Settings menu. The Configur...",""],
["html_remove_fog_zones_1.htm","Remove fog zones","Remove fog zones To remove fog zones: 1. Click the Fog Zone button. 2. Select the appropriate zone number in the zone list. The selected zone is h...",""],
["html_reset_the_processor_to_factory.htm","Reset the processor to factory defaults","Reset the processor to factory defaults NOTE: Reset to Factory Defaults should only be performed by a qualified Rhythm technician. This option wip...",""],
["html_second_topic.htm","Update an InSync Processor&#39;s software","Update a processor&#39;s software For optimal InSync Processor performance and to make sure your processor contains the latest features, you can insta...",""],
["html_set_fog_zones.htm","Set Fog Zones","Set Fog Zones NOTE: The following instructions pertain only to In|Sync, In|Sync:Fusion and In|Sync:Thermal installations. Fog zones are used by In...",""],
["html_set_fog_zones_1.htm","Set fog zones","Set fog zones NOTE: The following instructions pertain only to InSync and InSync:Fusion installations. Fog zones are used by InSync to verify that...",""],
["html_set_gps_coordinates.htm","Set GPS coordinates","Set GPS coordinates GPS coordinates are usually set only once, when you initially set up the processor at an intersection. We recommend that GPS c...",""],
["html_set_network_settings.htm","Set network settings","Set network settings NOTE: Setting the network settings should only be performed by a qualified Rhythm technician. This option is to be used when ...",""],
["html_set_refresh_rates.htm","Set refresh rates","Set the refresh rate The Refresh rate is the frequency at which the camera sends images to the InSync Web UI. You can select between: Fastest Ever...",""],
["html_set_system_time_and_date.htm","Set system time and date","Set system time and date NOTE: Setting the system time and date should only be performed by a qualified Rhythm technician. This option is to be us...",""],
["html_set_the_ntp_server.htm","Set the NTP server","Set the NTP server The Network Time Protocol (NTP) synchronizes the time of day among a set of distributed time servers and clients so that you ca...",""],
["html_set_the_system_name.htm","Set the system name","Set the system name NOTE: Setting the system name should only be performed by a qualified Rhythm technician. This option is to be used when you ne...",""],
["html_sub_chapter_2_1.htm","Confirm camera views","Confirm camera views Within the Multiple Camera view, there are several options available to you for viewing the cameras at the intersection. You ...",""],
["html_unassign_an_external_detector.htm","Unassign an External Detector","Unassign an External Detector To remove an external detector from a lane: 1. If the Configuration Utility is not open, select Configure Detectors ...",""],
["html_unassign_an_external_detector_1.htm","Unassign an external detector","Unassign a detector from a lane To remove an external detector from a lane: 1. Right-click the detector in the tree view. 2. Select Delete from th...",""],
["html_update_the_intersection.htm","Update the Intersection","Update the Intersection In order to save your configuration work, you must click the Update Intersection button to save configuration changes to t...",""],
["html_use_tail_processing.htm","Use tail processing","Use tail processing The CameraIO application tracks movements of vehicles within a detection zone - starting at the first video frame in which it ...",""],
["html_viewing_insync_status.htm","Viewing InSync status","Viewing InSync status The InSync system status displays the following information: Build: The build number of the InSync software running on the p...",""],
["html_view_intersection_history_logs.htm","View intersection history logs","View intersection history logs The InSync Processor collects and saves daily information into a historical log. This log can then be used for futu...",""],
["html_welcome_topic.htm","Restore an InSync configuration file","Restore a configuration file In the event that an InSync configuration file seems to be corrupt or not working the way you want it, you can revert...",""],
["insync_administrative_tasks.htm","InSync Administrative Tasks","In|Sync Administrative Tasks The functionality covered in this chapter should be preformed by users that have administrative access to In|Sync, as...",""],
["insync_installation_a_two_step.htm","InSync Installation: A two-step process","In|Sync Installation: A two-step process The installation of In|Sync can be broken into two phases: Hardware Installation Install the In|Sync equi...",""],
["intersection_naming.htm","Intersection Naming","Intersection Naming Verify that all intersections in the management group are labeled with meaningful names for identification purposes. Accepted ...",""],
["introduction.htm","Introduction","Introduction In|Sync is an adaptive traffic signal system developed by Rhythm Engineering that uses our In|Sync Processor’s artificial intelligenc...",""],
["logging_into_the_insync_webui.htm","Logging into the InSync WebUI","Logging into the InSync WebUI 1. Open your preferred web browser and type the processor&#39;s IP address in the Address bar. For example, type: http:/...",""],
["logging_into_the_insync_webui1_6.htm","Logging into the InSync WebUI","Logging into the In|Sync WebUI 1. Open your preferred web browser and type the processor&#39;s IP address in the Address bar. For example, type: http:...",""],
["manage_content_in_the_corridor.htm","Manage Content in the Corridor View","Manage Content in the Management Group View The Management Group View Designer can be found in the Settings menu. From this screen, you can change...",""],
["managing_content_in_the_portal.htm","Managing content in the Portal","Managing content in the Portal The Portal Designer can be found in the Settings sidebar. From this screen, you can define exactly which management...",""],
["managing_users.htm","Managing Users","Managing Users Logging into In|Sync requires you to have a user account. Setting up a user account requires you to have a user name and password, ...",""],
["monitoring_corridors.htm","Monitoring Corridors","Monitoring Management Groups You have the ability to monitor a management group by accessing any single processor because every processor is set u...",""],
["navigate_within_a_graph.htm","Navigate within a Graph","Navigate within a Graph To move within the graph, click anywhere on the graph and drag the graph until the area you want to view is displayed. ",""],
["open_the_configuration_in_cent.htm","Open the Configuration in CentralSync","Open the Configuration in CentralSync For convenience, InSync provides an option for you to open a corridor’s configuration within the CentralSync...",""],
["open_the_multiple_camera_view_.htm","Open the Multiple Camera View in its own Window","Open the Multiple Camera View in its own Window You can open the Multiple Camera view in a new window in full screen mode. Full screen mode hides ...",""],
["override_fog_mode_insync_insyn.htm","Override Fog Mode (InSync/InSync:Fusion Only)","Override Fog Mode (In|Sync/In|Sync:Fusion Only) NOTE: Overriding Fog Mode is only available to users with administration access. Selecting this bu...",""],
["overview.htm","What you need","What you need To access the In|Sync WebUI, you need one of the following Monitor and keyboard to access the WebUI from the In|Sync Processor Lapto...",""],
["pause_camera_images.htm","Pause Camera Images","Pause Camera Images To pause an individual camera view, click on it. A paused icon displays over the camera view. Clicking the pause icon resumes ...",""],
["pedestrian_graphs.htm","Pedestrian Graphs","Pedestrian Graphs The Pedestrian Graphs report displays two separate graphs: Pedestrian Counts and Pedestrian Hourly Summary. The Pedestrian Count...",""],
["period_graph.htm","Period Graph","Period Graph The Period Graph is useful for reviewing period lengths used by In|Sync. This graph shows the selected period for a configuration or ...",""],
["place_a_detection_on_a_phase_f.htm","Place a Detection on a Phase (force presence)","Place a Detection on a Phase (force presence) Clicking a phase&#39;s Force Presence field until it toggles to ON sends a vehicle detection for that ph...",""],
["place_a_manual_pedestrian_call.htm","Place a Manual Pedestrian Call","Place a Manual Pedestrian Call If the intersection is configured with pedestrian interception, manual Ped Call controls are also available to you....",""],
["place_a_manual_vehicle_call_on.htm","Place a Manual Vehicle Call on a Phase (manual call)","Place a Manual Vehicle Call on a Phase (manual call) Clicking a phase’s Manual Control field until it toggles to ON sends calls only from that pha...",""],
["place_the_system_into_detector.htm","Place the System into Detector Mode","Place the System into Detector Mode To place the intersection into detector mode and disable In|Sync adaptive mode, click Disable Adaptive. This m...",""],
["processor_graphs.htm","Processor Graphs","Processor Graphs Processor graphs displays two different graphs: the processor’s CPU temperature and the percentage of CPU being used (the load) t...",""],
["propagate_the_corridor_view_to.htm","Propagate the Corridor View to Several Processors","Propagate the Management Group View to Several Processors Propagating the Management Group View to other processors saves the management group vie...",""],
["propagate_the_portal_to_severa.htm","Propagate the Portal to Several Processors","Propagate the Portal to Several Processors Propagating the portal to other processors saves the Portal to every In|Sync Processor in the same mana...",""],
["rearrange_camera_views.htm","Rearrange Camera Views","Rearrange Camera Views You can move camera views around by clicking on a camera view and dragging it to the new position on the screen. To restore...",""],
["rearrange_corridor_content.htm","Rearrange Corridor Content","Rearrange Management Group Content You can move camera views within a column or move columns into a different order. To do so: 1. Place your mouse...",""],
["rearrange_the_content.htm","Rearrange the Content","Rearrange the Content To move content from one location to another: 1. Place your mouse over the title block of the content that you want to move....",""],
["reboot_a_camera.htm","Reboot a Camera","Reboot a Camera Rebooting a camera may help if a camera is experiencing any issues, like unresponsiveness, no image, low frame rate, stuck at an i...",""],
["remotely_controlling_an_inters.htm","Remotely Controlling an Intersection","Remotely Controlling an Intersection With In|Sync’s live camera views, you can see how In|Sync is responding to real-time traffic demand. You can ...",""],
["rename_phases.htm","Rename Phases","Rename Phases If In|Sync’s default phase naming scheme does not match your phase naming scheme, you can change In|Sync to match your scheme. The n...",""],
["reports.htm","Reports","Reports In|Sync records a tremendous amount of data. This data can be very useful in determining trends, reviewing what happened at an intersectio...",""],
["restore_a_configuration.htm","Restore a Configuration","Restore a Configuration The Restore configuration feature allows you to restore your previous configuration using the backup configuration file. I...",""],
["save_an_archive.htm","Save an Archive","Save an Archive In|Sync configuration files are automatically saved every time the configuration files change. In addition, you can download an ar...",""],
["save_the_corridor_view_to_the_.htm","Save the Corridor View to the Processor","Save the Management Group View to the Processor After defining content that you want displayed in the management group view and arranging the cont...",""],
["save_the_portal_to_the_process.htm","Save the Portal to the Processor","Save the Portal to the Processor After defining the content that you want displayed in the portal and arranging the content to your liking, you mu...",""],
["scheduling_a_video_recording.htm","Scheduling a Video Recording","Scheduling a Video Recording The reasons for wanting to record video taken at an intersection are varied. Having a recording of an intersection ca...",""],
["screen_conventions.htm","Screen Conventions","Screen Conventions Throughout the In|Sync WebUI, you will notice that certain areas of the screen always contain certain information and functiona...",""],
["set_the_ntp_server.htm","Set the NTP Server","Set the NTP Server For most In|Sync systems, the In|Sync Processors act as peers and automatically synchronize with each other. However, if your n...",""],
["set_the_refresh_rate.htm","Set the Refresh Rate","Set the Refresh Rate The Refresh rate is the frequency at which the camera sends images to the In|Sync WebUI. You can selected between: Fastest Ev...",""],
["set_up_a_multiple_processor_in.htm","Set up a Multiple Processor Intersection","Configure a Multiple Processor Intersection NOTE: The following instructions pertain only to In|Sync, In|Sync:Fusion and In|Sync:Thermal installat...",""],
["show_or_hide_phases.htm","Show or Hide Phases","Show or Hide Phases To show or hide phases on a graph, click the phase name on the legend, which displays on the right side of the graph. ",""],
["splits.htm","Splits","Splits The Splits report shows the range of green split times per phase, including the maximum, minimum and average. It also shows the percentage ...",""],
["statistics_report.htm","Statistics Report","Statistics Report The Statistics option offers seven different reports that provide a wide range of traffic data. By selecting Statistics, reports...",""],
["synching_time_after_inital_ins.htm","Synching time after inital install or processor replacement","Synching time after inital install or processor replacement The following steps should be performed after: Installing a new processor into an exis...",""],
["synchronize_ntp_time.htm","Synchronize NTP time","Synchronize NTP time The NTP Server page that is available through the Settings menu provides the ability to compare the time on a processor with ...",""],
["the_corridor_view.htm","The Corridor View","The Management Group View NOTE: The Management Group View is available to users that have cameras set to either View Only or View /Control and Man...",""],
["the_dashboard.htm","The Dashboard","The Dashboard After logging into In|Sync, the Dashboard screen displays. The dashboard is a screen that organizes and presents information in a wa...",""],
["the_map_view.htm","The Map View","The Map The Map view provides a graphical interpretation of the management group on a map image. It provides light status information at each inte...",""],
["the_portal_view.htm","Portal","Portal NOTE: The Portal menu item is available only to users with In|Sync Maintenance access (set in the Account Edit Users screen). The Managemen...",""],
["tmc_playback.htm","TMC Playback","TMC Playback The TMC Playback shows turning movements on each approach for each 15 minute period. This TMC data can be used to determine vehicle h...",""],
["toggle_a_camera_into_emergency.htm","Toggle a Camera into Emergency Mode (InSync/InSync:Fusion only)","Toggle a Camera into Emergency Mode (In|Sync/In|Sync:Fusion only) NOTE: Toggling a camera into Emergency mode is only available to users that have...",""],
["use_manual_controls.htm","Use Manual Controls","Use Manual Controls NOTE: Manual intersection control is available to users with Camera View/Control and Manual Traffic Controls permissions turne...",""],
["vehicle_graphs.htm","Vehicle Graphs","Vehicle Graphs The Vehicle Graphs report displays two separate graphs: Vehicle Counts and Vehicle Hourly Summary. The Vehicle Counts graph shows t...",""],
["viewing_an_intersection.htm","Viewing an Intersection","Viewing an Intersection There are several ways to watch the operation of an intersection. You can choose to look at all cameras at the intersectio...",""],
["viewing_a_single_camera.htm","Viewing a Single Camera","Viewing a Single Camera The single camera view allows for a more in-depth look from a single camera. From this screen you can choose which camera ...",""],
["viewing_failed_login_attempts.htm","Viewing Failed Login Attempts","Viewing Failed Login Attempts Any failed log in attempts are recorded by the In|Sync WebUI and can be viewed through the Invalid Logins screen. To...",""],
["viewing_insync_intersection_st.htm","Viewing InSync Intersection Status","Viewing In|Sync Intersection Status In addition to viewing all the cameras at an intersection through the Multiple Camera view, you can also see i...",""],
["viewing_multiple_cameras_at_an.htm","Viewing Multiple Cameras at an Intersection","Viewing Multiple Cameras at an Intersection Within the Multiple Camera view, there are several options available to you for viewing the cameras at...",""],
["viewing_processor_status.htm","Viewing Processor Status","Viewing Processor Status You can also obtain important hardware performance information regarding the In|Sync Processor from the Multiple Camera v...",""],
["view_a_recording.htm","View a Recording","View a Recording In|Sync recordings are stored as MJPEG files. You can view MJPEG files via several video players or within Safari or Google Chrom...",""],
["view_camera_status.htm","View Camera Status","View Camera Status Camera status information is available at the bottom of the Single Camera View. To view information about the camera, scroll to...",""],
["view_graph_details.htm","View Graph Details","View Graph Details You can view the data points within the graph by hovering the mouse over a plotted point. Detailed graph data displays in a too...",""],
["webui_ports.htm","WebUI Ports","WebUI Ports The following ports must be open to use the WebUI: 80: WebUI (http port) 443: WebUI (https port) 554: RTSP port 4520: Device control a...",""],
["what_are_processed_views_.htm","What are Unprocessed Views?","What are Unprocessed Views? Unprocessed mode simply means that the view you see is the raw footage that is coming straight from the camera. ",""],
["what_are_processed_views_2.htm","What are Processed Views?","What are Processed Views? The processed view (the default view) is the raw footage coming from the camera, plus information indicating the current...",""],
["what_is_adaptive_mode_.htm","What is Adaptive Mode?","What is Adaptive Mode? Adaptive mode is a state in which the In|Sync Processor analyzes queue and spontaneously chooses the phases and sequences t...",""],
["what_is_cameraio_.htm","What is CameraIO?","What is CameraIO? Every once in a while, the term &#8220;CameraIO&#8221; appears in the In|Sync WebUI Guide. The term &#8220;CameraIO&#8221; refers to the part of the In|...",""],
["what_is_cartoon_view_.htm","What is Cartoon View?","What is Cartoon View? In addition to being able to view processed or unprocessed views from the camera, there is an viewing option available from ...",""],
["what_is_detector_mode.htm","What is Detector Mode?","What is Detector Mode? Detector mode is a state in which the In|Sync Processor simply sends detections directly to the controller, allowing the co...",""],
["what_is_supervision_.htm","What is SuperVision?","What is SuperVision? In addition to seeing CameraIO every once in a while in the In|Sync WebUI Guide, you may also see the term \"SuperVision.\" &#8220;Su...",""],
["why_use_corridor_status_.htm","Why Use Corridor Status?","Why use Status? The Status page is a great troubleshooting tool for diagnosing network communication problems.From this page, you can concentrate ...",""],
["why_use_the_portal_view_.htm","Why use the Portal?","Why use the Portal? The Portal is a great way to consolidate access to views across management groups. For instance, you may have In|Sync Processo...",""],
["working_with_graphs.htm","Working with Graphs","Working with Graphs There are several options for analyzing graphs in further detail. Show or hide phases To show or hide phases on a graph, click...",""],
["zoom_in_on_an_area_of_the_grap.htm","Zoom in on an Area of the Graph","Zoom in on an Area of the Graph To enlarge an area of the map, double-click on the area of the map that you want enlarged, or roll your mouse’s mi...",""]];
